export default {
  servicename: "A1-Service",
  fileRootUrl: "",
  samplePost: ["https://xxxx", "FORM", "POST"],
  sampleGet: ["https://xxxxx", "FORM", "GET", "w"],
  playerlist: ["https://mltd.ecs32.top/filelist", "FORM", "POST"],
  audio: ["https://mltd.ecs32.top/ecs-music", "FORM", "POST"],
  audioInfo: ["https://mltd.ecs32.top/ecs-music", "FORM", "POST"],
  searchInfo: ["https://163.lpddr5.cn/search", "FORM", "GET", "w"],
  searchLrcInfo: ["https://163.lpddr5.cn/lyric", "FORM", "GET", "w"],
  createInfo: ["https://mltd.ecs32.top/ecs-music-create", "FORM", "POST"],
  artist: {
    "[2019.01.30] Poppin'on!": "Poppin'Party",
    "A_PPP": "Poppin'Party",
    "G_Cover": "BGP Cover",
    "F_Roselia": "Roselia",
    "H_RAS": "RAS",
    "I_Spec": "BGP CL",
    "B_Char": "BGP CS",
    "E_PP":"Pastel*Palettes",
    "Aimi": "愛美",
    "InoriMinase": "水瀬いのり",
    "UchidaMaya": "内田真礼",
    "TrySail": "TrySail",
    "Asakuramomo": "麻倉もも",
    "OnishiAguri":"大西亜玖璃",
    "Claris":"Claris",
    "HoyoMix":"HoyoMix",
    "Inst":"Inst"
  },
}
